---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: alpine
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports: 
        - containerPort: 8080
      args:
        - sleep 
        - 1d
