---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    purpose: svcdemo
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - targetPort: 80
      port: 80
      nodePort: 3000