---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  selector:
    app: nginx
  type: ClusterIP
  clusterIP: "None"
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
      protocol: TCP