---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
  labels:
    app: spc
    purpose: spcdemo
spec:
  type: ClusterIP
  selector:
    app: spc
  ports:
    - targetPort: 30000
      port: 8080