---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels:
    app: spc
    purpose: svcdemo
spec:
  replicas: 3
  minReadySeconds: 1
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
        - name: spc
          image: jagadeeshmurru/spc:1
          ports:
            - containerPort: 8080
              protocol: TCP