---
apiVersion: v1
kind: ReplicationController
metadata:
  name: spc-rc
  labels:
    purpose: rcdemo
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    app: spc1
  template:
    metadata:
      labels:
        app: spc1
        release: v1.1
    spec:
      containers:
        - name: spc
          image: jagadeeshmurru/spc:1
          ports:
            - containerPort: 8080
              protocol: TCP