apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    purpose: svcdemo
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - targetPort: 8080
      port: 8080