apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: nop
  strategy:
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: nop
    spec:
      containers:
      - name: spc
        image: jagadeeshmurru/nop:1
        ports:
        - containerPort: 5000
