---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx
    env: test
spec:
  containers: 
    - name: nginx1
      image: nginx:1.25
      ports: 
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    app: nginx
    env: dev
spec:
  containers: 
    - name: nginx2
      image: nginx:1.25
      ports: 
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod3
  labels:
    app: nginx
    env: usr
spec:
  containers: 
    - name: nginx3
      image: nginx:1.25
      ports: 
        - containerPort: 80
          protocol: TCP