apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: replicaset
  labels: 
    app: jenkins
    type: rs 
spec: 
  minReadySeconds: 3
  replicas: 4
  selector: 
    matchLabels: 
      type: rs
  template: 
    metadata: 
      name: jenkins-rs
      labels:
        app: jenkins
        release: v1.1
    spec: 
      initContainers: 
        - name: nginx1
          image: nginx
          ports: 
            - containerPort: 80
              protocol: TCP
      containers: 
        - name: jenkins
          image: jenkins/jenkins
          ports:
          - containerPort: 8080
            protocol: TCP